### ISSUE TITLE
platinum/iridium singularities

### ISSUE THREAD

**Issue by narckotick** [Uncryptical/EquivalenceCraft---In-The-Sky#1]
i found some trouble to craft the platinum and iridium singularities.
It seem like ther is no receipes for thoose two singularities 

hope you should be able to fix this in order to being able to continue my fantastic adventure ;-)

**Comment by Uncryptical** [comment]
Will do! I do apologize as I did glance over some items and will still end up fixing/adding in more items that are still untouched. I will release another patch to fix your current issue.

I hope you're enjoying the modpack!
