### ISSUE TITLE
Barrels, drums, storage & more

### ISSUE THREAD

**Issue by Redpyroangel** [Uncryptical/EquivalenceCraft---In-The-Sky#2]
Im having a few issues with this mod. any time i place the metal crates in world the show up as black. They will not accept any upgrade and when putting an item in to them they are holding 64X0. it show an image of the items i put in to them but it holds 0 items.

**Comment by Uncryptical** [comment]
Hey I'm sorry to hear that there's an issue with that specific mod. Could you send me a picture of how the bug is occurring?

**Comment by Redpyroangel** [comment]
![metalcrateissues](https://user-images.githubusercontent.com/110629841/183243662-c1751e97-979f-48ba-9ccc-59131c6a63cc.png)

**Comment by Redpyroangel** [comment]
sorry couldnt figure out how to do this last time. im loading the world now after the updates see if it fixed its self

**Comment by Redpyroangel** [comment]
so i found out my issues. pulling the crates out of the projecte transmutaion tablet breaks them. if i craft them outside of that and in a crafting table they work normally

**Comment by Uncryptical** [comment]
Thanks for letting me know how the issue occurred! I apologize that the Barrels, Drums, Storage, & More Mod is giving you that issue, I will look for another solution in the meantime.
